apiVersion: v1
kind: Service
metadata:
  name: kiosk
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiosk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 8080
      protocol: TCP
    {{- end }}
  selector:
    app: {{ template "kiosk.fullname" . }}
    release: {{ .Release.Name }}
