apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: johns-account-deletable-spaces
spec:
  space:
    clusterRole: kiosk-space-admin
    templateInstances:
    - spec:
        template: space-restrictions
        # You can also use parameters here
        # parameters:
        # - name: DEFAULT_CPU_REQUESTS
        #   value: "1"
  subjects:
  - kind: User
    name: john
    apiGroup: rbac.authorization.k8s.io
