apiVersion: config.kiosk.sh/v1alpha1
kind: Template
metadata:
  name: redis
resources:
  helm:
    releaseName: redis
    chart:
      repository:
        name: redis
        repoUrl: https://charts.bitnami.com/bitnami
    values: |
      redisPort: 6379
      # Use a predefined parameter here
      # You can also use annotations on the namespace 
      # with ${namespace.metadata.annotations.myAnnotation}
      myOtherValue: ${namespace}
